name: gym_tracker
description: App para organizar e acompanhar treinos de academia.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ringtone_player: ^4.0.0
  shared_preferences: ^2.2.2

  # Gerenciamento de estado
  flutter_riverpod: ^2.5.1

  # Rotas
  go_router: ^14.2.1

  # Datas e formatação
  intl: ^0.19.0
  fl_chart: ^0.68.0

  # Banco de dados local (Drift)
  drift: ^2.16.0
  drift_sqflite: ^2.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  test: ^1.24.9
  fake_async: ^1.3.1
  # Code Quality
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  

  # Geradores de código (Drift)
  drift_dev: ^2.16.0

# Utilities
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
